config/routes.rb
Rails.application.routes.draw do
	root to: "articles#index"
  resources :articles do
  	resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	has_attached_file :image, :styles => {:medium => "300x300>", :thumb => "150x150>"}
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]


	def tag_list
		tags.collect do |tg|
			tg.name
		end.join(", ")
	end

	def tag_list=(tags_string)
        tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
        self.tags = new_or_found_tags
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	def index
		@articles = Article.all
	end
	def new
		@article = Article.new
	end
	def create
=begin
		@article = Article.new
		@article.title = params[:article][:title]
		@article.body = params[:article][:body]
=end

=begin
	
        @article = Article.new(
                title: params[:article][:title],
                body: params[:article][:body])
=end
       
       # @article = Artical.new(params[:article])
		@article=Article.new(article_params)
		@article.save
		redirect_to article_path(@article.id)
	end
	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id=@article.id
	end 
	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		flash.notice = "Article #{@article.title}, Deleted!"
		redirect_to articles_path
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update(article_params)
		flash.notice = "Article #{@article.title}, updated!"
		redirect_to article_path(@article)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	include CommentsHelper
  def create
    @comment = Comment.new(com_helper)
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	def index
		@tags = Tag.all
	end
	def show
		@tag = Tag.find(params[:id])
	end

	def destroy
		@tag = Tag.find(params[:id])
		@tag.delete
		redirect_to tags_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
		params.require(:article).permit(:title, :body, :tag_list, :image)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
	def com_helper
		params.require(:comment).permit(:author_name, :body)
	end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
 <ul>
    <% @article.errors.full_messages do |error| %>
        <li><%= error %></li>
     <% end %>
 </ul>

 <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
 </p>
 <p>
    <%= f.label :body %>
    <%= f.text_area :body %>
 </p>

 <p>
    <%= f.label :tag_list %>
    <%= f.text_area :tag_list %>
 </p>

 <p>
  <%= f.label :Attached_Image %><br />
  <% if @article.image.exists? %>
      <%= image_tag @article.image.url(:medium) %><br/>
  <% end %>
</p>

<p>
  <%= f.label :image, "Attach a New Image" %><br/>
  <%= f.file_field :image %>
 </p>
   
 <p>
    <%= f.submit %>
 </p>
<% end %>

app/views/articles/edit.html.erb
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), class: 'article_title', id: "article_#{article.id}" %>
    </li>
  <% end %>
  <%= link_to "Create New Article", new_article_path, class: 'new_article' %> 
</ul>

app/views/articles/new.html.erb
<%= render partial: 'form' %>

  

app/views/articles/show.html.erb
<h1><%= @article.title %></h1><br />
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<p><%= image_tag @article.image.url(:medium) %></p>

<p><%= @article.body %></p>

<h3>Comments (<%= @article.comments.size %>)</h3>

<%= render partial: 'articles/comment', collection: @article.comments %>

<%= render partial: 'comments/form' %>

<%= link_to "<< Back to Articles List", articles_path %>
<%= link_to "delete", article_path(@article), data: {confirm: "Do you really want to delete?"}, method: :delete %>
<%= link_to "edit", edit_article_path(@article.id) %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="flash"><%=flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<h1> List Of Available Tags </h1>
<ul><% @tags.each do |tag| %>
	<li><%= link_to tag.name, tag_path(tag) %> <p> Delete tag : <%= link_to "delete", tag_path(tag), method: :delete%></p></li>
<% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>